version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 10.99.99.99:80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: weepee
      WORDPRESS_DB_PASSWORD: weepee
      WORDPRESS_DB_NAME: weepee
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins

  db:
    image: ${WEEPEE_MYSQL_IMAGE}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: weepee
      MYSQL_USER: weepee
      MYSQL_PASSWORD: weepee
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
